### ISSUE TITLE
scipy required for LMSDiscreteScheduler

### ISSUE THREAD

**Issue by robinkoehler** [quickwick/stable-diffusion-win-amd-ui#2]
Just playing around with different schedulers, and it would appear that with a standard ONNX config, "scipy" is missing. This throws the following error if LMSDiscrete is selected:

LMSDiscrete
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Robin\.conda\envs\ldm\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "text2img_ui.py", line 31, in change_scheduler
    scheduler = LMSDiscreteScheduler(tensor_format="np")
  File "d:\AI\stable-diffusion\virtualenv\lib\site-packages\diffusers\utils\dummy_scipy_objects.py", line 11, in __init__
    requires_backends(self, ["scipy"])
  File "d:\AI\stable-diffusion\virtualenv\lib\site-packages\diffusers\utils\import_utils.py", line 262, in requires_backends
    raise ImportError("".join(failed))
ImportError:
LMSDiscreteScheduler requires the scipy library but it was not found in your environment. You can install it with pip: `pip install
scipy`

pip install scipy fixed the issue. DDIM and PNDM were fine without it though

**Comment by quickwick** [comment]
Thanks, I forgot that I'd done that. It's been added to the readme in https://github.com/quickwick/stable-diffusion-win-amd-ui/commit/8fe8ab63be3955c59347b5d17a242823c905b194.
